project:
  type: website
  output-dir: _site

website:
  title: "RiverStyx"
  google-analytics: "GTM-WF59D6KK"
  search: false
  sidebar: 
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - section: "Cohorts"
        contents:
        - href: defining-cohorts-sql.qmd
          text: Defining Cohorts in SQL
        - href: webapi-cohort.qmd
          text: Getting Cohorts using WebAPI
        - href: phenotype-library.qmd
          text: Phenotype Library and Cohort Diagnostics
      - section: "Use Cases"
        contents:
        - href: characterization.qmd
          text: Characterization
        - href: population-lv-estimation.qmd
          text: Population Level Estimation
        - href: patient-lv-prediction.qmd
          text: Patient Level Prediction
      - section: "Data Quality"
        contents:
        - href: achilles.qmd
          text: Achilles
        - href: dqd.qmd
          text: Data Quality Dashboard
      
  navbar:
    search: false
    pinned: true
    tools:
      - icon: github
        href: https://github.com/mccullen/riverstyx
        target: _blank
editor:
  markdown:
    cannonical: true

format:
  html:
    toc-expand: 5
    df-print: paged
    theme: cosmo
    css: resources/styles.css
    toc: true
    grid: 
      # Just force it to take up all available space
      body-width: 5000px
