---
execute:
  eval: false
---

```{r}
checks <- DataQualityDashboard::listDqChecks()
```

```{r}
summary(checks)
```

```{r}
checks$checkDescriptions
```

```{r}
checks$tableChecks
```

```{r}
#| eval: false
datasetName = "GiBleed"
dbms = "sqlite"

datasetLocation <- Eunomia::getDatabaseFile(
  datasetName = datasetName, 
  dbms = dbms, 
  databaseFile = tempfile(fileext = ".sqlite")
)
connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = dbms, server = datasetLocation)
connection = DatabaseConnector::connect(connectionDetails = connectionDetails)
Eunomia::createCohorts(connectionDetails)
DatabaseConnector::getTableNames(connection, databaseSchema = 'main')
```

```{r}
#| eval: false
base_dir = "resources/artifacts/dqd"
DataQualityDashboard::executeDqChecks(
  connectionDetails,
  cdmDatabaseSchema = "main",
  resultsDatabaseSchema = "main",
  cdmSourceName = "Eunomia",
  outputFile = "synthea.json",
  outputFolder = base_dir)
```

```{r}
# Note json_path must be an absolute path...
json_path <- file.path(getwd(), base_dir, "synthea.json")
DataQualityDashboard::viewDqDashboard(jsonPath = json_path)
     
```
