# RiverStyx

RiverStyx is a playground for exploring the OHDSI [HADES](https://ohdsi.github.io/Hades/){target="_blank"} packages.

Launch interactive tutorials or view outputs directly on this website using the sidebar links or the tutorial links below.

If you need to quickly query synthetic data, check out [Eirene](https://eirene.netlify.app/playground){target="_blank"}.

## Usage

You can view the output of the tutorials on this web page, but if you want an interactive playground, you have two options: RStudio and Binder.

### RStudio

The best way to run this app is by using RStudio. This approach ensures full functionality, including Shiny apps, which may not perform well in Binder, your other option.

**Prerequisites**

-   [RStudio](https://posit.co/download/rstudio-desktop/)
-   [Java](https://www.java.com/download/ie_manual.jsp)
-   [Git](https://git-scm.com/downloads)
-   [Python](https://www.python.org/downloads/) (only for certain R packages, such as PatientLevelPrediction)
-   Various R packages (depending on the tutorial)

After satisfying the prerequisites, just clone the repository and open in RStudio as a Quarto project, and open the Quarto document of the tutorial you are interested in.

``` bash
git clone https://github.com/mccullen/riverstyx.git
```

### Binder

You can also run the app in a Binder environment. However, note that Binder may not handle RShiny apps well.

Please note that these environments may take some time to load and could fail. If it fails, try refreshing. Once launched, navigate to the 'riverstyx' directory and open the Quarto document you are interested in.

-   [RStudio](https://mybinder.org/v2/gh/mccullen/riverstyx-env/main?urlpath=rstudio){target="_blank"}: Interactive RStudio environment with HADES tutorials.
-   [Launcher](https://mybinder.org/v2/gh/mccullen/riverstyx-env/main){target="_blank"}: JupyterHub launcher page for accessing other tools and applications.

## Tutorials

### Defining Cohorts

-   [Defining Cohorts in SQL](defining-cohorts-sql.qmd)\
    *SQL-based cohort definition using the Eunomia GiBleed dataset in R.*
-   [Defining Cohorts in Atlas](defining-cohorts-atlas.qmd)\
    *Atlas cohort definition using the Eunomia GiBleed dataset in R.*
-   [Phenotype Library](phenotype-library.qmd)\
    *Use the PhenotypeLibrary R package to view OHDSI-vetted phenotypes and view cohort diagnostics.*

### Use Cases

Direct links to non-interactive outputs of the Quarto tutorials within the environment for easy and quick access.

-   [Characterization](characterization.qmd)\
    *Use the above cohort for AMI to do some characterizations using FeatureExtraction*
-   [Population Estimation](population-lv-estimation.qmd)\
    *What is the risk of gastrointentional (GI) bleed in new users of celecoxib compared to new users of diclofenac?*
-   [Patient Level Prediction](patient-lv-prediction.qmd)\
    *In patients that started using NSAIDs for the first time, predict who will develop a gastrointestinal (GI) bleed in the next year.*

### Data Quality

-   [Achilles](achilles.qmd)
-   [Data Quality Dashboard](dqd.qmd)
